apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.storage.dataAccessPodName }}
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    env:
      - name: LD_PRELOAD
        value: "{{ .Values.envVars.ldPreload }}"
      - name: http_proxy
        value: "{{ .Values.envVars.httpProxy }}"
      - name: https_proxy
        value: "{{ .Values.envVars.httpsProxy }}"
      - name: no_proxy
        value: "{{ .Values.envVars.noProxy }}"
      - name: ftp_proxy
        value: "{{ .Values.envVars.ftpProxy }}"
      - name: socks_proxy
        value: "{{ .Values.envVars.socksProxy }}"
    volumeMounts:
    - name: pvc-volume
      mountPath: {{ .Values.storage.pvcMountPath }}
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: {{ .Values.storage.pvcName }}
