apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.storage.resources }}
