name: Style Checks
on:
  pull_request:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches: '**'
    paths: '**'

# installs dependencies and runs the linter
jobs:
  style-test:
    runs-on: [ aia-devops ]
    container:
      image: amr-registry.caas.intel.com/aiops/tlt-dev
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Install virtualenv
      run: pip install virtualenv
    - name: Run linter
      run: |
        make lint
