name: Unit Test
on:
  pull_request:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths:
      - '**'
jobs:
  unit-test:
    runs-on: [ xai-tlt ]
    container:
      image: ${{ vars.GHA_IMAGE }}
      options: --shm-size=4GB
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
        MODEL_DIR: /tmp/tlt_cached_models/torch
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /tf_dataset/dataset/transfer_learning:/tmp/data
        - /localdisk/tlt_cached_models/torch:/tmp/tlt_cached_models/torch
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run Unit Test
        shell: bash
        continue-on-error: false
        run: make unittest
